kind: pipeline
type: docker
name: blog

clone:
  disable: true

steps:
  - name: scp project
    image: appleboy/drone-ssh
    pull: if-not-exists
    settings:
      host: 175.24.174.22
      username:
        from_secret: username
      password:
        from_secret: password
      port: 22
      script:
        - rm -rf /root/blog
        - git clone --recurse-submodules --remote-submodules git@github.com:HecMisio/blog.git
  - name: build public
    image: appleboy/drone-ssh
    pull: if-not-exists
    settings:
      host: 175.24.174.22
      username:
        from_secret: username
      password:
        from_secret: password
      port: 22
      script:
        - cd /root/blog
        - hugo
  - name: deploy blog
    image: appleboy/drone-ssh
    pull: if-not-exists
    settings:
      host: 175.24.174.22
      username:
        from_secret: username
      password:
        from_secret: password
      port: 22
      script:
        - docker rm -f blog
        - docker rmi blog:latest
        - cd /root/blog
        - docker build -t blog:latest .
        - cd /root/nginx/blog
        - docker run -itd --name blog
          -v $PWD/default.conf:/etc/nginx/conf.d/default.conf
          -v $PWD/cert/hecmisio.com_bundle.crt:/etc/nginx/hecmisio.com_bundle.crt
          -v $PWD/cert/hecmisio.com.key:/etc/nginx/hecmisio.com.key
          -p 1313:443 blog:latest
        - rm -rf /root/blog

trigger:
  branch:
    - main
  event:
    - push